# Generated by Django 5.0.1 on 2024-01-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_lost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost',
            name='department',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lost',
            name='item_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lost',
            name='item_lost',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lost',
            name='lost_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lost',
            name='lost_place',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lost',
            name='student_name',
            field=models.CharField(max_length=25),
        ),
    ]
