# Generated by Django 5.0.1 on 2024-01-28 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_lost', '0002_alter_lost_department_alter_lost_item_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10, null=True)),
                ('register_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item_lost.lost')),
            ],
        ),
    ]
