# Generated by Django 5.0.1 on 2024-01-25 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_category', models.CharField(max_length=100)),
                ('found_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('found_place', models.TextField()),
            ],
        ),
    ]
