# Generated by Django 5.0.1 on 2024-01-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_found', '0003_found_found_date_alter_found_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found',
            old_name='found_place',
            new_name='location',
        ),
    ]
