# Generated by Django 5.0.1 on 2024-01-31 18:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.IntegerField(blank=True, null=True, verbose_name=django.contrib.auth.models.User)),
                ('student_name', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('item_name', models.CharField(max_length=50)),
                ('item_category', models.CharField(max_length=50)),
                ('lost_date', models.DateField(blank=True, null=True)),
                ('location', models.TextField()),
            ],
        ),
    ]
