# Generated by Django 4.2.7 on 2024-01-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("first", "First"),
                            ("second", "Second"),
                            ("third", "Third"),
                            ("fourth", "Fourth"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("cse", "Computer Science Engineering"),
                            ("it", "Information Technology"),
                            ("ec", "Electronics And Communication Engineering"),
                            ("ee", "Electrical Engineering"),
                            ("au", "Automobile Engineering"),
                            ("me", "Mechanical Engineering"),
                        ],
                        max_length=100,
                    ),
                ),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
