# Generated by Django 4.2.7 on 2024-02-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lost_and_found_app", "0003_lostitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("found_location", models.CharField(max_length=100)),
                ("found_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "item_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="found_item_images/"
                    ),
                ),
                (
                    "finder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lost_and_found_app.user",
                    ),
                ),
                (
                    "lost_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lost_and_found_app.lostitem",
                    ),
                ),
            ],
        ),
    ]
